In [1]:
import warnings
warnings.filterwarnings('ignore')
from Model_test import *
from Load_and_Clean_data import *
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import pandas_profiling
from sklearn.decomposition import PCA

In [2]:
pd.options.display.max_columns = 90

## Load, Clean and Save


In [2]:
# Load and clean the data
df = load_raw_data()
df = clean_data(df)

# get features and target
X,y = df_featues_target(df)

# save to a file
save_X_y(X,y)


In [3]:
#load from file
X,y = load_X_y()

In [ ]:
# pandas_profiling.ProfileReport(df)

## Train Test Split

In [4]:
X_train, X_test, y_train, y_test = scale_train_test_split(X,y)

## Base Model

In [5]:
models, model_names = train_model(X_train, y_train)

Running AdaBoost
Running GradientBoost
Running Logistic Regresion
Running DecisionTree_gini
Running DecisionTree_entropy


In [6]:
y_train_predicts = predict_all(X_train, y_train, models)

In [7]:
y_test_predicts = predict_all(X_test, y_test, models)

In [8]:

print('--- Train data ---')
for i,y_train_pred in enumerate(y_train_predicts):
    display_acc_and_f1_score(y_train, y_train_pred, model_names[i])
print('\n\n--- Test data ---')
for i,y_test_pred in enumerate(y_test_predicts):
    display_acc_and_f1_score(y_test, y_test_pred, model_names[i])

--- Train data ---
Model: AdaBoost
Accuracy: 0.5822152926995441
F1-Score: 0.5822152926995441
Model: GradientBoost
Accuracy: 0.5924741889838059
F1-Score: 0.5924741889838059
Model: Logistic Regresion
Accuracy: 0.5715764372936429
F1-Score: 0.5715764372936429
Model: DecisionTree_gini
Accuracy: 0.5896834547455584
F1-Score: 0.5896834547455584
Model: DecisionTree_entropy
Accuracy: 0.5867617001205387
F1-Score: 0.5867617001205387


--- Test data ---
Model: AdaBoost
Accuracy: 0.5793962738778398
F1-Score: 0.5793962738778398
Model: GradientBoost
Accuracy: 0.5837591384325131
F1-Score: 0.5837591384325131
Model: Logistic Regresion
Accuracy: 0.5681550192594922
F1-Score: 0.5681550192594922
Model: DecisionTree_gini
Accuracy: 0.5718890024369153
F1-Score: 0.5718890024369153
Model: DecisionTree_entropy
Accuracy: 0.571495951576134
F1-Score: 0.571495951576134


In [ ]:
# Decision Tree overfitting because we did not limit number of splits yet

## Iteration #2

In [9]:
from imblearn.over_sampling import SMOTE
from collections import Counter

sm = SMOTE(random_state=109)
X_new_train, y_new_train = sm.fit_sample(X_train, y_train)



In [10]:
print(np.unique(y_new_train, return_counts=True))
np.unique(y, return_counts=True)

(array([0, 1, 2]), array([41148, 41148, 41148]))


(array([0, 1, 2]), array([54864, 11357, 35545]))

In [11]:
type(X_new_train), type(y_new_train)

(numpy.ndarray, numpy.ndarray)

In [12]:
type(X_test), type(y_test)

(pandas.core.frame.DataFrame, pandas.core.series.Series)

In [13]:
models, model_names = train_model(X_new_train, y_new_train)

Running AdaBoost
Running GradientBoost
Running Logistic Regresion
Running DecisionTree_gini
Running DecisionTree_entropy


In [14]:
y_new_train_predicts = predict_all(X_new_train, y_new_train, models)

In [15]:
y_new_test_predicts = predict_all(np.array(X_test), np.array(y_test), models)

In [16]:

print('--- Train data ---')
for i, y_new_train_pred in enumerate(y_new_train_predicts):
    display_acc_and_f1_score(y_new_train, y_new_train_pred, model_names[i])
print('\n\n--- Test data ---')
for i,y_new_test_pred in enumerate(y_new_test_predicts):
    display_acc_and_f1_score(y_test, y_new_test_pred, model_names[i])

--- Train data ---
Model: AdaBoost
Accuracy: 0.5685736042253977
F1-Score: 0.5685736042253977
Model: GradientBoost
Accuracy: 0.6070201872914034
F1-Score: 0.6070201872914034
Model: Logistic Regresion
Accuracy: 0.5965133987881145
F1-Score: 0.5965133987881145
Model: DecisionTree_gini
Accuracy: 0.5543242279900198
F1-Score: 0.5543242279900198
Model: DecisionTree_entropy
Accuracy: 0.5505897410971776
F1-Score: 0.5505897410971776


--- Test data ---
Model: AdaBoost
Accuracy: 0.5266488483609779
F1-Score: 0.5266488483609779
Model: GradientBoost
Accuracy: 0.5745224432041506
F1-Score: 0.5745224432041506
Model: Logistic Regresion
Accuracy: 0.5592327647197547
F1-Score: 0.5592327647197547
Model: DecisionTree_gini
Accuracy: 0.5299504755915415
F1-Score: 0.5299504755915415
Model: DecisionTree_entropy
Accuracy: 0.5202814244163195
F1-Score: 0.5202814244163195


## Iteration #3

In [17]:
len(X.columns)

81

In [ ]:
from sklearn.decomposition import PCA
import numpy as np

pca_1 = PCA(n_components=20)
pca_2 = PCA(n_components=40)
pca_3 = PCA(n_components=60)

principalComponents = pca_1.fit_transform(X)
principalComponents = pca_2.fit_transform(X)
principalComponents = pca_3.fit_transform(X)

print(np.sum(pca_1.explained_variance_ratio_))
print(np.sum(pca_2.explained_variance_ratio_))
print(np.sum(pca_3.explained_variance_ratio_))





# print(pca_1.explained_variance_ratio_)
# print(pca_2.explained_variance_ratio_)
# print(pca_3.explained_variance_ratio_)
# print(np.sum(pca_2.explained_variance_ratio_))
# print(np.sum(pca_3.explained_variance_ratio_))

In [18]:
pca = PCA(n_components=2)
principalComponents = pca.fit_transform(X)
print(np.sum(pca.explained_variance_ratio_))

0.8743319127661393


In [19]:
pca_df = pd.DataFrame(principalComponents, columns= ['PCA1','PCA2'])

In [20]:
X_train_pca, X_test_pca, y_train_pca, y_test_pca = scale_train_test_split(pca_df,y)

In [21]:
models, model_names = train_model(X_train_pca, y_train_pca)

Running AdaBoost
Running GradientBoost
Running Logistic Regresion
Running DecisionTree_gini
Running DecisionTree_entropy


In [22]:
y_train_predicts = predict_all(X_train_pca, y_train_pca, models)
y_test_predicts = predict_all(X_test_pca, y_test_pca, models)

In [23]:
print('--- Train data ---')
for i, y_new_train_pred in enumerate(y_train_predicts):
    display_acc_and_f1_score(y_train, y_new_train_pred, model_names[i])
print('\n\n--- Test data ---')
for i,y_new_test_pred in enumerate(y_test_predicts):
    display_acc_and_f1_score(y_test, y_new_test_pred, model_names[i])

--- Train data ---
Model: AdaBoost
Accuracy: 0.5390833813741418
F1-Score: 0.5390833813741418
Model: GradientBoost
Accuracy: 0.5404328913578953
F1-Score: 0.5404328913578953
Model: Logistic Regresion
Accuracy: 0.42175462501965305
F1-Score: 0.42175462501965305
Model: DecisionTree_gini
Accuracy: 0.542581625700959
F1-Score: 0.542581625700959
Model: DecisionTree_entropy
Accuracy: 0.5423326869660919
F1-Score: 0.5423326869660919


--- Test data ---
Model: AdaBoost
Accuracy: 0.5385189843565757
F1-Score: 0.5385189843565757
Model: GradientBoost
Accuracy: 0.5390692555616696
F1-Score: 0.5390692555616696
Model: Logistic Regresion
Accuracy: 0.4180882006131593
F1-Score: 0.4180882006131593
Model: DecisionTree_gini
Accuracy: 0.5368288656552158
F1-Score: 0.5368288656552158
Model: DecisionTree_entropy
Accuracy: 0.5363965097083563
F1-Score: 0.5363965097083563


## Iteration #4 setup a pipeline

In [5]:
# grid search over Desicion Trees
grid = find_best_tree_clf(X_train,  y_train)

Fitting 5 folds for each of 30 candidates, totalling 150 fits


[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done  46 tasks      | elapsed:    5.7s
[Parallel(n_jobs=2)]: Done 150 out of 150 | elapsed:   26.5s finished


In [6]:
y_pred = grid.predict(X_train)
display_acc_and_f1_score(y_train, y_pred, 'tree CV')

y_pred = grid.predict(X_test)
display_acc_and_f1_score(y_test, y_pred, 'tree CV')


Model: tree CV
Accuracy: 0.5780226403228342
F1-Score: 0.5780226403228342
Model: tree CV
Accuracy: 0.5753871550978696
F1-Score: 0.5753871550978696


In [9]:
grid.best_estimator_
grid.best_score_

0.5765814160683402

In [8]:
grid.cv_results_['mean_test_score']

array([0.56498611, 0.56498611, 0.56498611, 0.56772444, 0.56772444,
       0.56772444, 0.57658142, 0.57658142, 0.57658142, 0.57258529,
       0.57269011, 0.57276872, 0.54647293, 0.54659085, 0.54643363,
       0.56344007, 0.56344007, 0.56344007, 0.56831403, 0.56831403,
       0.56831403, 0.57656831, 0.57656831, 0.57656831, 0.57303076,
       0.57313558, 0.57310938, 0.54832032, 0.54839893, 0.54904093])

In [11]:
## logistic grid search CV
lr_grid = find_best_logistic(X_train, y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits


[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done  46 tasks      | elapsed:  7.4min
[Parallel(n_jobs=2)]: Done  50 out of  50 | elapsed:  7.9min finished


In [14]:
lr_grid.cv_results_

y_pred = lr_grid.predict(X_train)
display_acc_and_f1_score(y_train, y_pred, 'tree CV')

y_pred = lr_grid.predict(X_test)
display_acc_and_f1_score(y_test, y_pred, 'tree CV')

Model: tree CV
Accuracy: 0.5716026413709974
F1-Score: 0.5716026413709974
Model: tree CV
Accuracy: 0.5682336294316485
F1-Score: 0.5682336294316485


In [ ]:
gbt_clf = GradientBoostingClassifier()
gbt_clf.fit(X_train, y_train)
models.append(gbt_clf)

In [10]:
logistic = LogisticRegression()

pipe = Pipeline([('logistic', logistic)])
C = np.logspace(-4, 4, 50)
penalty = ['l1', 'l2']

parameters = dict(logistic__C=C,
                  logistic__penalty=penalty)

clf = GridSearchCV(pipe, parameters)


In [11]:
clf.fit(X_train, y_train)

KeyboardInterrupt: 

In [ ]:
print('Best Penalty:', clf.best_estimator_.get_params()['logistic__penalty'])
print('Best C:', clf.best_estimator_.get_params()['logistic__C'])

## Columns to inspect

    - Admission_type_id
  a  - discharge_disposition_id
    - admission_source_id
    - number_of_lab_procedures
    